"""Initial PostgreSQL schema baseline; frozen at the first Alembic revision."""

from alembic import op
import sqlalchemy as sa

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation_groups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'environment_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'environment_id', 'platform', 'external_id')
    )
    op.create_index('idx_conversation_groups_name', 'ai_conversation_groups', ['tenant_id', 'environment_id', 'name'], unique=False)
    op.create_table('ai_session_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('user_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('environment_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('input_ordinal', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_messages_owner', 'ai_session_messages', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_session_messages_order', 'ai_session_messages', ['tenant_id', 'environment_id', 'session_id', 'seq'], unique=True)
    op.create_index('idx_session_messages_session', 'ai_session_messages', ['session_id', 'seq'], unique=False)
    op.create_table('ai_session_usage',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('uncached_input_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_write_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_ttl', sa.Text(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('reasoning_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd', sa.Float(precision=53), server_default=sa.text('0'), nullable=False),
    sa.Column('pricing_catalog_version', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('environment_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_usage_owner', 'ai_session_usage', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_session_usage_order', 'ai_session_usage', ['tenant_id', 'environment_id', 'session_id', 'seq'], unique=True)
    op.create_index('idx_session_usage_session', 'ai_session_usage', ['session_id', 'seq'], unique=False)
    op.create_index('idx_session_usage_model', 'ai_session_usage', ['model'], unique=False)
    op.create_table('ai_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('parent_session_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Float(precision=53), nullable=False),
    sa.Column('ended_at', sa.Float(precision=53), nullable=True),
    sa.Column('last_active', sa.Float(precision=53), nullable=True),
    sa.Column('uncached_input_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cache_write_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('reasoning_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd', sa.Float(precision=53), server_default=sa.text('0'), nullable=False),
    sa.Column('user_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('environment_id', sa.Text(), server_default=sa.text("'default'"), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Text(), server_default=sa.text("'private'"), nullable=False),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('prompt_snapshot_id', sa.Text(), nullable=True),
    sa.Column('next_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_turn_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('context_revision', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('active_run_id', sa.Text(), nullable=True),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.Float(precision=53), nullable=True),
    sa.Column('lease_epoch', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_owner', 'ai_sessions', ['tenant_id', sa.literal_column('last_active DESC')], unique=False)
    op.create_index('idx_sessions_parent', 'ai_sessions', ['parent_session_id'], unique=False)
    op.create_index('idx_sessions_user', 'ai_sessions', ['user_id', sa.literal_column('last_active DESC')], unique=False)
    op.create_index('uq_sessions_scope_id', 'ai_sessions', ['tenant_id', 'environment_id', 'id'], unique=True)
    op.create_table('ai_state_meta',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('fnd_auth_api_keys',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('last_used_at', sa.Float(precision=53), nullable=True),
    sa.Column('revoked_at', sa.Float(precision=53), nullable=True),
    sa.Column('hash_algo', sa.Text(), server_default=sa.text("'v1'"), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_client', 'fnd_auth_api_keys', ['client_id'], unique=False)
    op.create_index('idx_api_keys_prefix', 'fnd_auth_api_keys', ['prefix'], unique=False)
    op.create_index('idx_api_keys_user', 'fnd_auth_api_keys', ['user_id'], unique=False)
    op.create_table('fnd_auth_group_memberships',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'group_id', 'user_id')
    )
    op.create_index('idx_auth_group_memberships_user', 'fnd_auth_group_memberships', ['tenant_id', 'user_id'], unique=False)
    op.create_table('fnd_auth_groups',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index('idx_auth_groups_tenant', 'fnd_auth_groups', ['tenant_id', 'name'], unique=False)
    op.create_table('fnd_auth_local_credentials',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('must_change', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_local_credentials_user', 'fnd_auth_local_credentials', ['user_id'], unique=True)
    op.create_table('fnd_auth_membership_attributes',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('business_unit', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.create_index('idx_membership_attributes_business_unit', 'fnd_auth_membership_attributes', ['tenant_id', 'business_unit'], unique=False)
    op.create_index('idx_membership_attributes_department', 'fnd_auth_membership_attributes', ['tenant_id', 'department'], unique=False)
    op.create_table('fnd_auth_memberships',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Text(), nullable=False),
    sa.Column('roles', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('active_role', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_index('idx_memberships_org', 'fnd_auth_memberships', ['org_id'], unique=False)
    op.create_table('fnd_auth_orgs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('disabled', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fnd_auth_roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('menu_id', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('active_from', sa.Float(precision=53), nullable=True),
    sa.Column('active_to', sa.Float(precision=53), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index('idx_roles_tenant', 'fnd_auth_roles', ['tenant_id'], unique=False)
    op.create_table('fnd_auth_users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('last_login_at', sa.Float(precision=53), nullable=True),
    sa.Column('disabled', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'human'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject')
    )
    op.create_index('idx_users_email', 'fnd_auth_users', ['email'], unique=False)
    op.create_table('fnd_classification_flow_map',
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('flow_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('parameters', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('fnd_email_dispatches',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('flow_name', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fnd_emails',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account', sa.Text(), nullable=False),
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('in_reply_to', sa.Text(), nullable=True),
    sa.Column('references_ids', sa.Text(), nullable=True),
    sa.Column('from_addr', sa.Text(), nullable=True),
    sa.Column('to_addr', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('date_header', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), server_default=sa.text("'inbound'"), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fnd_flow_definitions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index('idx_flow_definitions_tenant', 'fnd_flow_definitions', ['tenant_id', 'name'], unique=False)
    op.create_table('fnd_flow_deployments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('flow_name', sa.Text(), nullable=False),
    sa.Column('schedule_raw', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('concurrency_limit', sa.BigInteger(), nullable=True),
    sa.Column('enforce_parameter_schema', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('paused', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_run_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.Column('user_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_deployments_owner', 'fnd_flow_deployments', ['tenant_id', 'name'], unique=False)
    op.create_index('idx_deployments_flow', 'fnd_flow_deployments', ['flow_name'], unique=False)
    op.create_table('fnd_flow_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('occurred', sa.Float(precision=53), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('related', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('follows', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_occurred', 'fnd_flow_events', [sa.literal_column('occurred DESC')], unique=False)
    op.create_index('idx_events_resource', 'fnd_flow_events', ['resource_id'], unique=False)
    op.create_index('idx_events_owner', 'fnd_flow_events', ['tenant_id', sa.literal_column('occurred DESC')], unique=False)
    op.create_index('idx_events_type', 'fnd_flow_events', ['event'], unique=False)
    op.create_table('fnd_flow_run_edges',
    sa.Column('downstream', sa.Text(), nullable=False),
    sa.Column('upstream', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default=sa.text("'data'"), nullable=False),
    sa.PrimaryKeyConstraint('downstream', 'upstream', 'kind')
    )
    op.create_table('fnd_flow_run_states',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('state_type', sa.Text(), nullable=False),
    sa.Column('state_name', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('state_details', sa.Text(), nullable=True),
    sa.Column('orchestration', sa.Text(), nullable=True),
    sa.Column('at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('run_id', 'seq')
    )
    op.create_index('idx_states_run', 'fnd_flow_run_states', ['run_id', 'seq'], unique=False)
    op.create_table('fnd_flow_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('state_type', sa.Text(), nullable=False),
    sa.Column('state_name', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parent_run_id', sa.Text(), nullable=True),
    sa.Column('flow_run_id', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('retries', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('started_at', sa.Float(precision=53), nullable=True),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.Column('finished_at', sa.Float(precision=53), nullable=True),
    sa.Column('owner_id', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.Float(precision=53), nullable=True),
    sa.Column('user_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.Column('definition_id', sa.Text(), nullable=True),
    sa.Column('definition_version', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_parent', 'fnd_flow_runs', ['parent_run_id'], unique=False)
    op.create_index('idx_runs_state', 'fnd_flow_runs', ['state_type'], unique=False)
    op.create_index('idx_runs_owner', 'fnd_flow_runs', ['tenant_id', 'user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_runs_created', 'fnd_flow_runs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_runs_flow', 'fnd_flow_runs', ['flow_run_id'], unique=False)
    op.create_index('idx_runs_heartbeat', 'fnd_flow_runs', ['heartbeat_at'], unique=False)
    op.create_table('fnd_nav_functions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('active_from', sa.Float(precision=53), nullable=True),
    sa.Column('active_to', sa.Float(precision=53), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_index('idx_functions_tenant', 'fnd_nav_functions', ['tenant_id'], unique=False)
    op.create_table('fnd_nav_menu_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('menu_id', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('function_id', sa.Text(), nullable=True),
    sa.Column('ref_menu_id', sa.Text(), nullable=True),
    sa.Column('access', sa.Text(), server_default=sa.text("'write'"), nullable=False),
    sa.Column('label_override', sa.Text(), nullable=True),
    sa.Column('icon_override', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('active_from', sa.Float(precision=53), nullable=True),
    sa.Column('active_to', sa.Float(precision=53), nullable=True),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_items_function', 'fnd_nav_menu_items', ['function_id'], unique=False)
    op.create_index('idx_menu_items_menu', 'fnd_nav_menu_items', ['menu_id'], unique=False)
    op.create_index('idx_menu_items_ref', 'fnd_nav_menu_items', ['ref_menu_id'], unique=False)
    op.create_table('fnd_nav_menus',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('active_from', sa.Float(precision=53), nullable=True),
    sa.Column('active_to', sa.Float(precision=53), nullable=True),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.Column('tenant_id', sa.Text(), server_default=sa.text("'local'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nav_menus_tenant', 'fnd_nav_menus', ['tenant_id'], unique=False)
    op.create_table('fnd_nav_pages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('fnd_nav_versions',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.Float(precision=53), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('ai_session_contexts',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('context_revision', sa.BigInteger(), nullable=False),
    sa.Column('first_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('token_count', sa.BigInteger(), nullable=False),
    sa.Column('source_digest', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.CheckConstraint('first_seq >= 0 AND last_seq >= first_seq'),
    sa.ForeignKeyConstraint(['tenant_id', 'environment_id', 'session_id'], ['ai_sessions.tenant_id', 'ai_sessions.environment_id', 'ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'environment_id', 'session_id', 'context_revision')
    )
    op.create_table('ai_session_participants',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('access_level', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'environment_id', 'session_id'], ['ai_sessions.tenant_id', 'ai_sessions.environment_id', 'ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'environment_id', 'session_id', 'user_id')
    )
    op.create_table('ai_session_prompt_snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('references_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('definition_revision', sa.Text(), nullable=True),
    sa.Column('digest', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'environment_id', 'session_id'], ['ai_sessions.tenant_id', 'ai_sessions.environment_id', 'ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_snapshots_session', 'ai_session_prompt_snapshots', ['tenant_id', 'environment_id', 'session_id', 'created_at'], unique=False)
    op.create_table('ai_session_routes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('environment_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('connection_id', sa.Text(), nullable=False),
    sa.Column('chat_id', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('agent_id', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'environment_id', 'session_id'], ['ai_sessions.tenant_id', 'ai_sessions.environment_id', 'ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'environment_id', 'platform', 'connection_id', 'chat_id', 'thread_id', 'agent_id')
    )
    op.create_index('idx_session_routes_session', 'ai_session_routes', ['tenant_id', 'environment_id', 'session_id'], unique=False)
    op.create_table('fnd_email_classifications',
    sa.Column('email_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(precision=53), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'rule'"), nullable=False),
    sa.Column('created_at', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['fnd_emails.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'label')
    )
    op.create_table('fnd_flow_attrs',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('definition_id', sa.Text(), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('scope_path', sa.Text(), nullable=False),
    sa.Column('attribute_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=False),
    sa.Column('candidates', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'definition_id'], ['fnd_flow_definitions.tenant_id', 'fnd_flow_definitions.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'definition_id', 'version', 'scope_path', 'attribute_id'),
    sa.UniqueConstraint('tenant_id', 'definition_id', 'version', 'scope_path', 'name')
    )
    op.create_table('fnd_flow_definition_versions',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('definition_id', sa.Text(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('graph', sa.Text(), nullable=False),
    sa.Column('published_at', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'definition_id'], ['fnd_flow_definitions.tenant_id', 'fnd_flow_definitions.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'definition_id', 'version')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    raise RuntimeError("Gyrfalcon schema revisions are forward only")
