import React,{useEffect,useState}from"react";import{CalendarClock,Play,Pause,Trash2,Plus,RefreshCw}from"lucide-react";import{api}from"../lib/api";
type Graph={id:string;name:string;published:boolean;published_version:number|null};type Deployment={id:string;name:string;short_name:string;definition_id:string;version:number;schedule:string|null;parameters:Record<string,unknown>;input_schema?:Record<string,unknown>;allowed_service_account_ids?:string[];paused:boolean|number;next_run_at:number|null};
const button:React.CSSProperties={border:"1px solid var(--border)",borderRadius:5,padding:"5px 8px",background:"transparent",color:"var(--fg)",cursor:"pointer",display:"inline-flex",gap:5,alignItems:"center"};
export function FlowDeploymentsPage(){const[deps,setDeps]=useState<Deployment[]>([]);const[graphs,setGraphs]=useState<Graph[]>([]);const[loading,setLoading]=useState(true);const[show,setShow]=useState(false);const[name,setName]=useState("");const[short,setShort]=useState("");const[flow,setFlow]=useState("");const[schedule,setSchedule]=useState("");const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
const load=async()=>{setLoading(true);try{const[d,g]=await Promise.all([api.getVisualDeployments(),api.getFlowGraphs()]);setDeps(d.deployments||[]);setGraphs((g.graphs||[]).filter((x:Graph)=>x.published));}catch{setDeps([]);setGraphs([]);}finally{setLoading(false);}};useEffect(()=>{load();},[]);
async function create(){if(!name.trim()||!short.trim()||!flow){setMessage("Name, endpoint name, and a published flow are required.");return;}try{await api.createVisualDeployment({name:name.trim(),short_name:short.trim().toLowerCase(),definition_id:flow,version:null,schedule:schedule.trim()||null,input_schema:{},parameters:{},allowed_service_account_ids:[],paused:false});setShow(false);setName("");setShort("");setSchedule("");setMessage("");await load();}catch(e:any){setMessage(e.message||"Could not create deployment");}}
async function run(d:Deployment){setBusy(d.id);try{const r=await api.runVisualDeployment(d.id);setMessage(`Run queued: ${r.run_id}`);}catch(e:any){setMessage(e.message||"Could not queue run");}finally{setBusy("");}}
async function toggle(d:Deployment){try{await api.updateVisualDeployment(d.id,{name:d.name,short_name:d.short_name,definition_id:d.definition_id,version:d.version,schedule:d.schedule,input_schema:d.input_schema||{},parameters:d.parameters||{},allowed_service_account_ids:d.allowed_service_account_ids||[],paused:!d.paused});await load();}catch(e:any){setMessage(e.message||"Could not update deployment");}}
async function remove(d:Deployment){if(!confirm(`Delete deployment “${d.name}”?`))return;try{await api.deleteVisualDeployment(d.id);await load();}catch(e:any){setMessage(e.message||"Could not delete deployment");}}
return <div style={{padding:0,maxWidth:1000}}><header style={{display:"flex",alignItems:"center",gap:10,marginBottom:16}}><CalendarClock size={17}/><h1 style={{fontSize:16,margin:0}}>Deployments</h1><span>{deps.length}</span><button style={{...button,marginLeft:"auto"}} onClick={load}><RefreshCw size={13}/> Refresh</button><button style={button} onClick={()=>setShow(v=>!v)}><Plus size={13}/> New</button></header>
{message&&<div style={{padding:8,marginBottom:10,background:"var(--card)",borderRadius:6}}>{message}<button onClick={()=>setMessage("")} style={{float:"right"}}>×</button></div>}{show&&<section style={{padding:14,marginBottom:14,border:"1px solid var(--border)",borderRadius:8,display:"grid",gap:8}}><input placeholder="Deployment name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Endpoint short name" value={short} onChange={e=>setShort(e.target.value)}/><select value={flow} onChange={e=>setFlow(e.target.value)}><option value="">Select published flow…</option>{graphs.map(g=><option key={g.id} value={g.id}>{g.name} (v{g.published_version})</option>)}</select><input placeholder="Schedule (optional)" value={schedule} onChange={e=>setSchedule(e.target.value)}/><div><button style={button} onClick={create}>Create deployment</button><button style={{...button,marginLeft:8}} onClick={()=>setShow(false)}>Cancel</button></div></section>}
{loading?"Loading…":!deps.length?<div style={{color:"var(--fg-muted)"}}>No deployments yet. Publish a flow, then create a deployment.</div>:deps.map(d=><article key={d.id} style={{border:"1px solid var(--border)",borderRadius:8,padding:13,marginBottom:9,background:"var(--card)"}}><div style={{display:"flex",alignItems:"center",gap:10}}><strong>{d.name}</strong><code>{d.short_name}</code><span>v{d.version}</span><span>{d.paused?"Paused":"Active"}</span><div style={{marginLeft:"auto",display:"flex",gap:6}}><button style={button} disabled={busy===d.id||!!d.paused} onClick={()=>run(d)}><Play size={13}/> Run</button><button style={button} onClick={()=>toggle(d)}>{d.paused?<Play size={13}/>:<Pause size={13}/>} {d.paused?"Resume":"Pause"}</button><button style={button} onClick={()=>remove(d)}><Trash2 size={13}/></button></div></div><div style={{fontSize:12,color:"var(--fg-muted)",marginTop:6}}>Flow {d.definition_id} · Schedule {d.schedule||"manual only"} · Next {d.next_run_at?new Date(d.next_run_at*1000).toLocaleString():"—"}</div></article>)}</div>}
